# -*- coding: utf-8 -*-
"""GMC_first_py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QwzaETn3B8yO93dajUC0drbH1HUTYz8d
"""



"""
#welcome to the World of Python!!

## Introducing the print function

`print` is a built-in function in Python and it is case sensitive"""

print("hello world")

print("my name is Olugbenga")

print("I'm learning about github and I am gonna add my work to a repository I cloned")